#pragma once


// 塗りつぶしモード
FWK_JSON_SERIALIZE_ENUM
(
	D3D12_FILL_MODE,
	FWK_JSON_ENUM_VALUE(D3D12_FILL_MODE_WIREFRAME),
	FWK_JSON_ENUM_VALUE(D3D12_FILL_MODE_SOLID)
)

// カリングモード
FWK_JSON_SERIALIZE_ENUM
(
	D3D12_CULL_MODE,
	FWK_JSON_ENUM_VALUE(D3D12_CULL_MODE_NONE),
	FWK_JSON_ENUM_VALUE(D3D12_CULL_MODE_FRONT),
	FWK_JSON_ENUM_VALUE(D3D12_CULL_MODE_BACK)
)

// 保守的ラスタライズ
FWK_JSON_SERIALIZE_ENUM
(
	D3D12_CONSERVATIVE_RASTERIZATION_MODE,
	FWK_JSON_ENUM_VALUE(D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF),
	FWK_JSON_ENUM_VALUE(D3D12_CONSERVATIVE_RASTERIZATION_MODE_ON)
)

// ブレンド係数
FWK_JSON_SERIALIZE_ENUM
(
	D3D12_BLEND,
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_ZERO),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_ONE),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_SRC_COLOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_SRC_COLOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_SRC_ALPHA),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_SRC_ALPHA),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_DEST_ALPHA),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_DEST_ALPHA),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_DEST_COLOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_DEST_COLOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_SRC_ALPHA_SAT),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_BLEND_FACTOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_BLEND_FACTOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_SRC1_COLOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_SRC1_COLOR),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_SRC1_ALPHA),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_INV_SRC1_ALPHA)
)

// ブレンド演算
FWK_JSON_SERIALIZE_ENUM
(
	D3D12_BLEND_OP,
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_OP_ADD),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_OP_SUBTRACT),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_OP_REV_SUBTRACT),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_OP_MIN),
	FWK_JSON_ENUM_VALUE(D3D12_BLEND_OP_MAX)
)

// 論理演算
FWK_JSON_SERIALIZE_ENUM
(
	D3D12_LOGIC_OP,
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_CLEAR),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_SET),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_COPY),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_COPY_INVERTED),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_NOOP),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_INVERT),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_AND),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_NAND),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_OR),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_NOR),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_XOR),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_EQUIV),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_AND_REVERSE),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_AND_INVERTED),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_OR_REVERSE),
	FWK_JSON_ENUM_VALUE(D3D12_LOGIC_OP_OR_INVERTED)
)

// 深度書き込み設定
FWK_JSON_SERIALIZE_ENUM
(
	D3D12_DEPTH_WRITE_MASK,
	FWK_JSON_ENUM_VALUE(D3D12_DEPTH_WRITE_MASK_ZERO),
	FWK_JSON_ENUM_VALUE(D3D12_DEPTH_WRITE_MASK_ALL)
)

// ステンシル操作
FWK_JSON_SERIALIZE_ENUM
(
	D3D12_STENCIL_OP,
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_KEEP),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_ZERO),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_REPLACE),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_INCR_SAT),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_DECR_SAT),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_INVERT),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_INCR),
	FWK_JSON_ENUM_VALUE(D3D12_STENCIL_OP_DECR)
)

// プリミティブトポロジー
FWK_JSON_SERIALIZE_ENUM
(
	D3D12_PRIMITIVE_TOPOLOGY_TYPE,
	FWK_JSON_ENUM_VALUE(D3D12_PRIMITIVE_TOPOLOGY_TYPE_UNDEFINED),
	FWK_JSON_ENUM_VALUE(D3D12_PRIMITIVE_TOPOLOGY_TYPE_POINT),
	FWK_JSON_ENUM_VALUE(D3D12_PRIMITIVE_TOPOLOGY_TYPE_LINE),
	FWK_JSON_ENUM_VALUE(D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE),
	FWK_JSON_ENUM_VALUE(D3D12_PRIMITIVE_TOPOLOGY_TYPE_PATCH)
)