#pragma once

FWK_JSON_SERIALIZE_ENUM
(
	DXGI_FORMAT,
	FWK_JSON_ENUM_VALUE(DXGI_FORMAT_UNKNOWN),
	FWK_JSON_ENUM_VALUE(DXGI_FORMAT_R8G8B8A8_UNORM),
	FWK_JSON_ENUM_VALUE(DXGI_FORMAT_R8G8B8A8_UNORM_SRGB)
)