#include "GameObjectTransformComponentMatrixUpdateHierarchicalModeInspector.h"

void FWK::GameObjectTransformComponentMatrixUpdateHierarchicalModeInspector::EditInspector(GameObjectTransformComponentMatrixUpdateHierarchicalMode& a_matrixUpdateHierarchicalMode)
{
    auto& l_calculateParentWorldMatrixEnumBitShift = a_matrixUpdateHierarchicalMode.GetMutableREFCalculateParentWorldMatrixEnumBitShift();

    l_calculateParentWorldMatrixEnumBitShift.EditInspector(k_calculateParentWorldMatrixEnumBitShiftCheckBoxSelectorLabel);
}