#include "StaticModelRegisterDrawRequestCascadeShadowStorategy.h"

void FWK::StaticModelRegisterDrawRequestCascadeShadowStorategy::Execute(StaticModelComponent& a_staticModelComponent)
{
	RegisterDrawRequestData<Graphics::StaticModelCascadeShadowPerObjectDrawRequest>(a_staticModelComponent);
}