#include "StaticModelRegisterDrawRequestCascadeShadowStrategy.h"

void FWK::StaticModelRegisterDrawRequestCascadeShadowStrategy::Execute(StaticModelComponent& a_staticModelComponent)
{
	RegisterDrawRequestData<Graphics::StaticModelCascadeShadowPerObjectDrawRequest>(a_staticModelComponent);
}