#pragma once

// InputLayout
FWK_JSON_SERIALIZE_ENUM
(
	D3D12_INPUT_CLASSIFICATION,
	FWK_JSON_ENUM_VALUE(D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA),
	FWK_JSON_ENUM_VALUE(D3D12_INPUT_CLASSIFICATION_PER_INSTANCE_DATA)
)